/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.usbcali.colegiousb.presentacion;

import co.edu.usbcali.colegiousb.logica.EmpleadoLogica;
import co.edu.usbcali.colegiousb.logica.IEmpleadoLogica;
import co.edu.usbcali.colegiousb.modelo.Empleado;
import javax.swing.JOptionPane;
/**
 *
 * @author FAVI
 */
public class InterfazCRUDEmpleado2 extends javax.swing.JFrame {
    private IEmpleadoLogica empleadoLogica = new EmpleadoLogica();
    
    /**
     * Creates new form InterfazCRUDEstudiante
     */
    
    public InterfazCRUDEmpleado2() {
        initComponents();
        botonTransparente();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Registrar Empleado");
    }
    
    public void botonTransparente(){
        btnHome4.setOpaque(false);
        btnHome4.setBorderPainted(false);
        btnHome4.setContentAreaFilled(false);
        BotonCrearEmpleado.setOpaque(false);
        BotonCrearEmpleado.setBorderPainted(false);
        BotonCrearEmpleado.setContentAreaFilled(false);
        BotonLimpiarEmpleado.setOpaque(false);
        BotonLimpiarEmpleado.setBorderPainted(false);
        BotonLimpiarEmpleado.setContentAreaFilled(false);
        BotonVisualizarEmpleado.setOpaque(false);
        BotonVisualizarEmpleado.setBorderPainted(false);
        BotonVisualizarEmpleado.setContentAreaFilled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCompleto = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        TextEmpleado = new javax.swing.JLabel();
        IconoEmpleado = new javax.swing.JLabel();
        btnHome4 = new javax.swing.JButton();
        TextoCabecera = new javax.swing.JLabel();
        Datos = new javax.swing.JPanel();
        IdEmpleado = new javax.swing.JLabel();
        TextIdEmpleado = new javax.swing.JTextField();
        RolEmpleado = new javax.swing.JLabel();
        NombreEmpleado = new javax.swing.JLabel();
        TextNombreEmpleado = new javax.swing.JTextField();
        EdadEmpleado = new javax.swing.JLabel();
        SexoEmpleado = new javax.swing.JLabel();
        SalarioEmpleado = new javax.swing.JLabel();
        TextSalarioEmpleado = new javax.swing.JTextField();
        TextEdadEmpleado = new javax.swing.JTextField();
        ComboSexoEmpleado = new javax.swing.JComboBox<>();
        ComboRolEmpleado = new javax.swing.JComboBox<>();
        Operadores = new javax.swing.JPanel();
        BotonCrearEmpleado = new javax.swing.JButton();
        BotonVisualizarEmpleado = new javax.swing.JButton();
        BotonLimpiarEmpleado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelCompleto.setBackground(new java.awt.Color(79, 134, 193));
        PanelCompleto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(178, 218, 250));

        TextEmpleado.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TextEmpleado.setForeground(new java.awt.Color(0, 61, 112));
        TextEmpleado.setText("Empleado");

        IconoEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/acuerdo.png"))); // NOI18N

        btnHome4.setBackground(new java.awt.Color(178, 218, 250));
        btnHome4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/back.png"))); // NOI18N
        btnHome4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnHome4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IconoEmpleado)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(TextEmpleado)))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnHome4)
                .addGap(106, 106, 106)
                .addComponent(TextEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IconoEmpleado)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        PanelCompleto.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 530));

        TextoCabecera.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        TextoCabecera.setForeground(new java.awt.Color(255, 255, 255));
        TextoCabecera.setText("Sistema Registro De Empleados");
        PanelCompleto.add(TextoCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        Datos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        Datos.setForeground(new java.awt.Color(255, 255, 255));
        Datos.setOpaque(false);

        IdEmpleado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        IdEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        IdEmpleado.setText("ID");

        TextIdEmpleado.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        RolEmpleado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RolEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        RolEmpleado.setText("Rol");

        NombreEmpleado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NombreEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        NombreEmpleado.setText("Nombre");

        TextNombreEmpleado.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        EdadEmpleado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        EdadEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        EdadEmpleado.setText("Edad");

        SexoEmpleado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SexoEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        SexoEmpleado.setText("Sexo");

        SalarioEmpleado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SalarioEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        SalarioEmpleado.setText("Salario");

        TextSalarioEmpleado.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        TextEdadEmpleado.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        ComboSexoEmpleado.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ComboSexoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        ComboRolEmpleado.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ComboRolEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aseador", "Profesor", "Coordinador", "Director", "Psicólogo", "Vigilante" }));

        javax.swing.GroupLayout DatosLayout = new javax.swing.GroupLayout(Datos);
        Datos.setLayout(DatosLayout);
        DatosLayout.setHorizontalGroup(
            DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(DatosLayout.createSequentialGroup()
                        .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreEmpleado)
                            .addComponent(EdadEmpleado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextNombreEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(TextEdadEmpleado)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DatosLayout.createSequentialGroup()
                        .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SexoEmpleado)
                            .addComponent(SalarioEmpleado))
                        .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DatosLayout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(TextSalarioEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosLayout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(ComboSexoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DatosLayout.createSequentialGroup()
                        .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IdEmpleado)
                            .addComponent(RolEmpleado))
                        .addGap(124, 124, 124)
                        .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextIdEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(ComboRolEmpleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        DatosLayout.setVerticalGroup(
            DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdEmpleado)
                    .addComponent(TextIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RolEmpleado)
                    .addComponent(ComboRolEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreEmpleado)
                    .addComponent(TextNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EdadEmpleado)
                    .addComponent(TextEdadEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SexoEmpleado)
                    .addComponent(ComboSexoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalarioEmpleado)
                    .addComponent(TextSalarioEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelCompleto.add(Datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 440, 310));

        Operadores.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Operadores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        Operadores.setOpaque(false);

        BotonCrearEmpleado.setBackground(new java.awt.Color(178, 218, 250));
        BotonCrearEmpleado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BotonCrearEmpleado.setForeground(new java.awt.Color(0, 61, 112));
        BotonCrearEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/anadir (1).png"))); // NOI18N
        BotonCrearEmpleado.setText("Crear");
        BotonCrearEmpleado.setBorderPainted(false);
        BotonCrearEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCrearEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCrearEmpleadoActionPerformed(evt);
            }
        });

        BotonVisualizarEmpleado.setBackground(new java.awt.Color(178, 218, 250));
        BotonVisualizarEmpleado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BotonVisualizarEmpleado.setForeground(new java.awt.Color(0, 61, 112));
        BotonVisualizarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/visualizacion-de-datos.png"))); // NOI18N
        BotonVisualizarEmpleado.setText("Visualizar");
        BotonVisualizarEmpleado.setBorderPainted(false);
        BotonVisualizarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonVisualizarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVisualizarEmpleadoActionPerformed(evt);
            }
        });

        BotonLimpiarEmpleado.setBackground(new java.awt.Color(178, 218, 250));
        BotonLimpiarEmpleado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BotonLimpiarEmpleado.setForeground(new java.awt.Color(0, 61, 112));
        BotonLimpiarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/limpieza-de-datos (1).png"))); // NOI18N
        BotonLimpiarEmpleado.setText("Limpiar");
        BotonLimpiarEmpleado.setBorderPainted(false);
        BotonLimpiarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonLimpiarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OperadoresLayout = new javax.swing.GroupLayout(Operadores);
        Operadores.setLayout(OperadoresLayout);
        OperadoresLayout.setHorizontalGroup(
            OperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperadoresLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(BotonCrearEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonVisualizarEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonLimpiarEmpleado)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        OperadoresLayout.setVerticalGroup(
            OperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperadoresLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(OperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonCrearEmpleado)
                    .addComponent(BotonVisualizarEmpleado)
                    .addComponent(BotonLimpiarEmpleado))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        PanelCompleto.add(Operadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 440, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCrearEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCrearEmpleadoActionPerformed
        try{
            Empleado empleado = new Empleado();
            empleado.setId(TextIdEmpleado.getText());
            empleado.setRol(ComboRolEmpleado.getSelectedItem().toString());
            empleado.setNombre(TextNombreEmpleado.getText());
            empleado.setEdad(TextEdadEmpleado.getText());
            empleado.setSexo(ComboSexoEmpleado.getSelectedItem().toString());
            empleado.setSalario(TextSalarioEmpleado.getText());

            if (TextIdEmpleado.getText().isEmpty() || TextNombreEmpleado.getText().isEmpty() || TextEdadEmpleado.getText().isEmpty() || TextSalarioEmpleado.getText().isEmpty()) {
                JOptionPane.showMessageDialog(PanelCompleto, "Todos los campos son obligatorios", "Registrar Empleado", JOptionPane.ERROR_MESSAGE);
            }
            
            if (empleadoLogica.validarEmpleadoId(empleado.getId())) {
                JOptionPane.showMessageDialog(PanelCompleto, "El Id debe ser único e irrepetible", "Registrar Empleado", JOptionPane.ERROR_MESSAGE);
            } else if (Integer.parseInt(empleado.getEdad()) > 18) {
                empleadoLogica.crearEmpleado(empleado);
                BotonLimpiarEmpleadoActionPerformed(evt);
                JOptionPane.showMessageDialog(PanelCompleto, "Se ha registrado el empleado: " + empleado.getNombre(), "Registrar Empleado", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(PanelCompleto, "El empleado debe ser mayor de edad", "Registrar Empleado", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
        } 
    }//GEN-LAST:event_BotonCrearEmpleadoActionPerformed

    private void BotonLimpiarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarEmpleadoActionPerformed
        TextIdEmpleado.setText(null);
        ComboRolEmpleado.setSelectedItem(null);
        TextNombreEmpleado.setText(null);
        TextEdadEmpleado.setText(null);
        ComboSexoEmpleado.setSelectedItem(null);
        TextSalarioEmpleado.setText(null);
    }//GEN-LAST:event_BotonLimpiarEmpleadoActionPerformed

    private void BotonVisualizarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVisualizarEmpleadoActionPerformed
        this.setVisible(false);
        new InterfazCRUDEmpleado().setVisible(true);
    }//GEN-LAST:event_BotonVisualizarEmpleadoActionPerformed

    private void btnHome4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome4ActionPerformed
        this.setVisible(false);
        new InterfazHomePage().setVisible(true);
    }//GEN-LAST:event_btnHome4ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InterfazCRUDEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InterfazCRUDEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InterfazCRUDEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InterfazCRUDEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new InterfazCRUDEmpleado2().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCrearEmpleado;
    private javax.swing.JButton BotonLimpiarEmpleado;
    private javax.swing.JButton BotonVisualizarEmpleado;
    private javax.swing.JComboBox<String> ComboRolEmpleado;
    private javax.swing.JComboBox<String> ComboSexoEmpleado;
    private javax.swing.JPanel Datos;
    private javax.swing.JLabel EdadEmpleado;
    private javax.swing.JLabel IconoEmpleado;
    private javax.swing.JLabel IdEmpleado;
    private javax.swing.JLabel NombreEmpleado;
    private javax.swing.JPanel Operadores;
    private javax.swing.JPanel PanelCompleto;
    private javax.swing.JLabel RolEmpleado;
    private javax.swing.JLabel SalarioEmpleado;
    private javax.swing.JLabel SexoEmpleado;
    private javax.swing.JTextField TextEdadEmpleado;
    private javax.swing.JLabel TextEmpleado;
    private javax.swing.JTextField TextIdEmpleado;
    private javax.swing.JTextField TextNombreEmpleado;
    private javax.swing.JTextField TextSalarioEmpleado;
    private javax.swing.JLabel TextoCabecera;
    private javax.swing.JButton btnHome4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
