/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.usbcali.colegiousb.presentacion;

/**
 *
 * @author joseph
 */
public class InterfazHomePage extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public InterfazHomePage() {
        initComponents();
        botonTransparente();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Inicio");
    }

    public void botonTransparente(){
        btnEstudiantes.setOpaque(false);
        btnEstudiantes.setBorderPainted(false);
        btnEstudiantes.setContentAreaFilled(false);
        btnEmpleados.setOpaque(false);
        btnEmpleados.setBorderPainted(false);
        btnEmpleados.setContentAreaFilled(false);
        btnActividades.setOpaque(false);
        btnActividades.setBorderPainted(false);
        btnActividades.setContentAreaFilled(false);
        btnEventos.setOpaque(false);
        btnEventos.setBorderPainted(false);
        btnEventos.setContentAreaFilled(false);
        btnMaterias.setOpaque(false);
        btnMaterias.setBorderPainted(false);
        btnMaterias.setContentAreaFilled(false);
        btnRegistroEstudiante.setOpaque(false);
        btnRegistroEstudiante.setBorderPainted(false);
        btnRegistroEstudiante.setContentAreaFilled(false);
        btnEventoMateria.setOpaque(false);
        btnEventoMateria.setBorderPainted(false);
        btnEventoMateria.setContentAreaFilled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PanelCompleto = new javax.swing.JPanel();
        PanelCabecera = new javax.swing.JPanel();
        ColegioUSB = new javax.swing.JLabel();
        Subtitulo = new javax.swing.JLabel();
        PanelMenu = new javax.swing.JPanel();
        Estudiante = new javax.swing.JLabel();
        Empleado = new javax.swing.JLabel();
        CrearEvento = new javax.swing.JLabel();
        Eventos = new javax.swing.JLabel();
        RegistroEstudiante = new javax.swing.JLabel();
        btnEstudiantes = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        btnActividades = new javax.swing.JButton();
        btnEventos = new javax.swing.JButton();
        btnMaterias = new javax.swing.JButton();
        btnRegistroEstudiante = new javax.swing.JButton();
        Actividades = new javax.swing.JLabel();
        btnEventoMateria = new javax.swing.JButton();
        Materias = new javax.swing.JLabel();
        CrearEvento1 = new javax.swing.JLabel();
        CrearEvento2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelCompleto.setBackground(new java.awt.Color(255, 255, 255));

        PanelCabecera.setBackground(new java.awt.Color(80, 134, 193));

        ColegioUSB.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        ColegioUSB.setForeground(new java.awt.Color(255, 255, 255));
        ColegioUSB.setText("ColegioUSB");

        Subtitulo.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        Subtitulo.setForeground(new java.awt.Color(255, 255, 255));
        Subtitulo.setText("Manejo de reportes para Colegios");

        javax.swing.GroupLayout PanelCabeceraLayout = new javax.swing.GroupLayout(PanelCabecera);
        PanelCabecera.setLayout(PanelCabeceraLayout);
        PanelCabeceraLayout.setHorizontalGroup(
            PanelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCabeceraLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addGroup(PanelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Subtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ColegioUSB, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelCabeceraLayout.setVerticalGroup(
            PanelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCabeceraLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(ColegioUSB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Subtitulo)
                .addGap(29, 29, 29))
        );

        PanelMenu.setBackground(new java.awt.Color(255, 255, 255));
        PanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Estudiante.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Estudiante.setForeground(new java.awt.Color(0, 61, 112));
        Estudiante.setText("Estudiantes");
        PanelMenu.add(Estudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        Empleado.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Empleado.setForeground(new java.awt.Color(0, 61, 112));
        Empleado.setText("Empleados");
        PanelMenu.add(Empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        CrearEvento.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CrearEvento.setForeground(new java.awt.Color(0, 61, 112));
        CrearEvento.setText("Estudiante - Materia");
        PanelMenu.add(CrearEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, -1));

        Eventos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Eventos.setForeground(new java.awt.Color(0, 61, 112));
        Eventos.setText("Eventos");
        PanelMenu.add(Eventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));

        RegistroEstudiante.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RegistroEstudiante.setForeground(new java.awt.Color(0, 61, 112));
        RegistroEstudiante.setText("Registrar");
        PanelMenu.add(RegistroEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 80, -1));

        btnEstudiantes.setForeground(new java.awt.Color(255, 255, 255));
        btnEstudiantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/leyendo.png"))); // NOI18N
        btnEstudiantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudiantesActionPerformed(evt);
            }
        });
        PanelMenu.add(btnEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 110, -1));

        btnEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/acuerdo.png"))); // NOI18N
        btnEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });
        PanelMenu.add(btnEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 130, -1));

        btnActividades.setForeground(new java.awt.Color(255, 255, 255));
        btnActividades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/lista.png"))); // NOI18N
        btnActividades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActividadesActionPerformed(evt);
            }
        });
        PanelMenu.add(btnActividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 110, -1));

        btnEventos.setForeground(new java.awt.Color(255, 255, 255));
        btnEventos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/calendario.png"))); // NOI18N
        btnEventos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventosActionPerformed(evt);
            }
        });
        PanelMenu.add(btnEventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 130, 130));

        btnMaterias.setForeground(new java.awt.Color(255, 255, 255));
        btnMaterias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/cuaderno-cerrado-y-boligrafo.png"))); // NOI18N
        btnMaterias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMateriasActionPerformed(evt);
            }
        });
        PanelMenu.add(btnMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        btnRegistroEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/registrarse.png"))); // NOI18N
        btnRegistroEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistroEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroEstudianteActionPerformed(evt);
            }
        });
        PanelMenu.add(btnRegistroEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 120, 130));

        Actividades.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Actividades.setForeground(new java.awt.Color(0, 61, 112));
        Actividades.setText("Actividades");
        PanelMenu.add(Actividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        btnEventoMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/organizador.png"))); // NOI18N
        btnEventoMateria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEventoMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventoMateriaActionPerformed(evt);
            }
        });
        PanelMenu.add(btnEventoMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 130, 130));

        Materias.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Materias.setForeground(new java.awt.Color(0, 61, 112));
        Materias.setText("Materias");
        PanelMenu.add(Materias, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        CrearEvento1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CrearEvento1.setForeground(new java.awt.Color(0, 61, 112));
        CrearEvento1.setText("Registrar");
        PanelMenu.add(CrearEvento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));

        CrearEvento2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CrearEvento2.setForeground(new java.awt.Color(0, 61, 112));
        CrearEvento2.setText("Evento - Materia");
        PanelMenu.add(CrearEvento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

        javax.swing.GroupLayout PanelCompletoLayout = new javax.swing.GroupLayout(PanelCompleto);
        PanelCompleto.setLayout(PanelCompletoLayout);
        PanelCompletoLayout.setHorizontalGroup(
            PanelCompletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
        );
        PanelCompletoLayout.setVerticalGroup(
            PanelCompletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCompletoLayout.createSequentialGroup()
                .addComponent(PanelCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventosActionPerformed
        this.setVisible(false);
        new InterfazCRUDEvento2().setVisible(true);
    }//GEN-LAST:event_btnEventosActionPerformed

    private void btnEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudiantesActionPerformed
        this.setVisible(false);
        new InterfazCRUDEstudiante2().setVisible(true);
    }//GEN-LAST:event_btnEstudiantesActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        this.setVisible(false);
        new InterfazCRUDEmpleado2().setVisible(true);
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActividadesActionPerformed
        this.setVisible(false);
        new InterfazCRUDActividad2().setVisible(true);
    }//GEN-LAST:event_btnActividadesActionPerformed

    private void btnMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateriasActionPerformed
        this.setVisible(false);
        new InterfazCRUDMateria2().setVisible(true);
    }//GEN-LAST:event_btnMateriasActionPerformed

    private void btnRegistroEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroEstudianteActionPerformed
        this.setVisible(false);
        new InterfazCRUDMateriaEstudiante2().setVisible(true);
    }//GEN-LAST:event_btnRegistroEstudianteActionPerformed

    private void btnEventoMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventoMateriaActionPerformed
        this.setVisible(false);
        new InterfazCRUDEventoMateria2().setVisible(true);
    }//GEN-LAST:event_btnEventoMateriaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InterfazHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InterfazHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InterfazHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InterfazHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new InterfazHomePage().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Actividades;
    private javax.swing.JLabel ColegioUSB;
    private javax.swing.JLabel CrearEvento;
    private javax.swing.JLabel CrearEvento1;
    private javax.swing.JLabel CrearEvento2;
    private javax.swing.JLabel Empleado;
    private javax.swing.JLabel Estudiante;
    private javax.swing.JLabel Eventos;
    private javax.swing.JLabel Materias;
    private javax.swing.JPanel PanelCabecera;
    private javax.swing.JPanel PanelCompleto;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JLabel RegistroEstudiante;
    private javax.swing.JLabel Subtitulo;
    private javax.swing.JButton btnActividades;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnEstudiantes;
    private javax.swing.JButton btnEventoMateria;
    private javax.swing.JButton btnEventos;
    private javax.swing.JButton btnMaterias;
    private javax.swing.JButton btnRegistroEstudiante;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
