/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.usbcali.colegiousb.presentacion;

import co.edu.usbcali.colegiousb.logica.EstudianteLogica;
import co.edu.usbcali.colegiousb.logica.GradoLogica;
import co.edu.usbcali.colegiousb.logica.IEstudianteLogica;
import co.edu.usbcali.colegiousb.logica.IGradoLogica;
import co.edu.usbcali.colegiousb.modelo.Estudiante;
import javax.swing.JOptionPane;
/**
 *
 * @author FAVI
 */
public class InterfazCRUDEstudiante2 extends javax.swing.JFrame {
    private IEstudianteLogica estudianteLogica = new EstudianteLogica();
    private IGradoLogica gradoLogica = new GradoLogica();
   
    /**
     * Creates new form InterfazCRUDEstudiante
     */
    
    public InterfazCRUDEstudiante2() {
        initComponents();
        botonTransparente();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Registrar Estudiante");
    }
    
    public void botonTransparente(){
        btnHome4.setOpaque(false);
        btnHome4.setBorderPainted(false);
        btnHome4.setContentAreaFilled(false);
        BotonCrearEstudiante.setOpaque(false);
        BotonCrearEstudiante.setBorderPainted(false);
        BotonCrearEstudiante.setContentAreaFilled(false);
        BotonLimpiarEstudiante.setOpaque(false);
        BotonLimpiarEstudiante.setBorderPainted(false);
        BotonLimpiarEstudiante.setContentAreaFilled(false);
        BotonVisualizarEstudiante.setOpaque(false);
        BotonVisualizarEstudiante.setBorderPainted(false);
        BotonVisualizarEstudiante.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCompleto = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        TextEstudiante = new javax.swing.JLabel();
        IconoEstudiante = new javax.swing.JLabel();
        btnHome4 = new javax.swing.JButton();
        TextoCabecera = new javax.swing.JLabel();
        Datos = new javax.swing.JPanel();
        IdEstudiante = new javax.swing.JLabel();
        TextIdEstudiante = new javax.swing.JTextField();
        NombreEstudiante = new javax.swing.JLabel();
        TextNombeEstudiante = new javax.swing.JTextField();
        EdadEstudiante = new javax.swing.JLabel();
        TextEdadEstudiante = new javax.swing.JTextField();
        SexoEstudiante = new javax.swing.JLabel();
        GradoEstudiante = new javax.swing.JLabel();
        UniformeEstudiante = new javax.swing.JLabel();
        TextUniformeEstudiante = new javax.swing.JTextField();
        ComboSexoEstudiante = new javax.swing.JComboBox<>();
        ComboGradoEstudiante = new javax.swing.JComboBox<>();
        Operadores = new javax.swing.JPanel();
        BotonCrearEstudiante = new javax.swing.JButton();
        BotonVisualizarEstudiante = new javax.swing.JButton();
        BotonLimpiarEstudiante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelCompleto.setBackground(new java.awt.Color(79, 134, 193));
        PanelCompleto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(178, 218, 250));

        TextEstudiante.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TextEstudiante.setForeground(new java.awt.Color(0, 61, 112));
        TextEstudiante.setText("Estudiante");

        IconoEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/leyendo.png"))); // NOI18N

        btnHome4.setBackground(new java.awt.Color(178, 218, 250));
        btnHome4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/back.png"))); // NOI18N
        btnHome4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(TextEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(IconoEstudiante))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnHome4)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnHome4)
                .addGap(113, 113, 113)
                .addComponent(TextEstudiante)
                .addGap(18, 18, 18)
                .addComponent(IconoEstudiante)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        PanelCompleto.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 530));

        TextoCabecera.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        TextoCabecera.setForeground(new java.awt.Color(255, 255, 255));
        TextoCabecera.setText("Sistema Registro De Estudiantes");
        PanelCompleto.add(TextoCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        Datos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        Datos.setForeground(new java.awt.Color(255, 255, 255));
        Datos.setOpaque(false);

        IdEstudiante.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        IdEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        IdEstudiante.setText("ID");

        TextIdEstudiante.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        NombreEstudiante.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NombreEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        NombreEstudiante.setText("Nombre");

        TextNombeEstudiante.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        EdadEstudiante.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        EdadEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        EdadEstudiante.setText("Edad");

        TextEdadEstudiante.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        SexoEstudiante.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SexoEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        SexoEstudiante.setText("Sexo");

        GradoEstudiante.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        GradoEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        GradoEstudiante.setText("Grado");

        UniformeEstudiante.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UniformeEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        UniformeEstudiante.setText("Uniforme");

        TextUniformeEstudiante.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        ComboSexoEstudiante.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ComboSexoEstudiante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        ComboSexoEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboSexoEstudianteActionPerformed(evt);
            }
        });

        ComboGradoEstudiante.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ComboGradoEstudiante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11" }));

        javax.swing.GroupLayout DatosLayout = new javax.swing.GroupLayout(Datos);
        Datos.setLayout(DatosLayout);
        DatosLayout.setHorizontalGroup(
            DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(DatosLayout.createSequentialGroup()
                        .addComponent(IdEstudiante)
                        .addGap(129, 129, 129)
                        .addComponent(TextIdEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DatosLayout.createSequentialGroup()
                        .addComponent(NombreEstudiante)
                        .addGap(96, 96, 96)
                        .addComponent(TextNombeEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DatosLayout.createSequentialGroup()
                            .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(GradoEstudiante)
                                .addComponent(UniformeEstudiante))
                            .addGap(85, 85, 85)
                            .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TextUniformeEstudiante)
                                .addComponent(ComboGradoEstudiante, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DatosLayout.createSequentialGroup()
                            .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(EdadEstudiante)
                                .addComponent(SexoEstudiante))
                            .addGap(114, 114, 114)
                            .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TextEdadEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                .addComponent(ComboSexoEstudiante, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        DatosLayout.setVerticalGroup(
            DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdEstudiante)
                    .addComponent(TextIdEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreEstudiante)
                    .addComponent(TextNombeEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EdadEstudiante)
                    .addComponent(TextEdadEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SexoEstudiante)
                    .addComponent(ComboSexoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GradoEstudiante)
                    .addComponent(ComboGradoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UniformeEstudiante)
                    .addComponent(TextUniformeEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        PanelCompleto.add(Datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 440, 310));

        Operadores.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Operadores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        Operadores.setOpaque(false);

        BotonCrearEstudiante.setBackground(new java.awt.Color(178, 218, 250));
        BotonCrearEstudiante.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BotonCrearEstudiante.setForeground(new java.awt.Color(0, 61, 112));
        BotonCrearEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/anadir (1).png"))); // NOI18N
        BotonCrearEstudiante.setText("Crear");
        BotonCrearEstudiante.setBorderPainted(false);
        BotonCrearEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCrearEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCrearEstudianteActionPerformed(evt);
            }
        });

        BotonVisualizarEstudiante.setBackground(new java.awt.Color(178, 218, 250));
        BotonVisualizarEstudiante.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BotonVisualizarEstudiante.setForeground(new java.awt.Color(0, 61, 112));
        BotonVisualizarEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/visualizacion-de-datos.png"))); // NOI18N
        BotonVisualizarEstudiante.setText("Visualizar");
        BotonVisualizarEstudiante.setBorderPainted(false);
        BotonVisualizarEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonVisualizarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVisualizarEstudianteActionPerformed(evt);
            }
        });

        BotonLimpiarEstudiante.setBackground(new java.awt.Color(178, 218, 250));
        BotonLimpiarEstudiante.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BotonLimpiarEstudiante.setForeground(new java.awt.Color(0, 61, 112));
        BotonLimpiarEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/limpieza-de-datos (1).png"))); // NOI18N
        BotonLimpiarEstudiante.setText("Limpiar");
        BotonLimpiarEstudiante.setBorderPainted(false);
        BotonLimpiarEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonLimpiarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarEstudianteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OperadoresLayout = new javax.swing.GroupLayout(Operadores);
        Operadores.setLayout(OperadoresLayout);
        OperadoresLayout.setHorizontalGroup(
            OperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperadoresLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(BotonCrearEstudiante)
                .addGap(18, 18, 18)
                .addComponent(BotonVisualizarEstudiante)
                .addGap(18, 18, 18)
                .addComponent(BotonLimpiarEstudiante)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        OperadoresLayout.setVerticalGroup(
            OperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonCrearEstudiante)
                    .addComponent(BotonVisualizarEstudiante)
                    .addComponent(BotonLimpiarEstudiante))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        PanelCompleto.add(Operadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 440, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCrearEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCrearEstudianteActionPerformed
        try{
            Estudiante estudiante = new Estudiante();
            estudiante.setId(TextIdEstudiante.getText());
            estudiante.setNombre(TextNombeEstudiante.getText());
            estudiante.setEdad(TextEdadEstudiante.getText());
            estudiante.setSexo(ComboSexoEstudiante.getSelectedItem().toString());
            estudiante.setGrado(gradoLogica.obtenerGradoPorId(Integer.parseInt(ComboGradoEstudiante.getSelectedItem().toString())));
            estudiante.setUniforme(TextUniformeEstudiante.getText());

            if (TextIdEstudiante.getText().isEmpty() || TextNombeEstudiante.getText().isEmpty() || TextEdadEstudiante.getText().isEmpty() || TextUniformeEstudiante.getText().isEmpty()) {
                JOptionPane.showMessageDialog(PanelCompleto, "Todos los campos son obligatorios", "Registrar Estudiante", JOptionPane.ERROR_MESSAGE);
            } 
            
            if (estudianteLogica.validarEstudianteId(estudiante.getId())) {
                JOptionPane.showMessageDialog(PanelCompleto, "El Id debe ser único e irrepetible", "Registrar Estudiante", JOptionPane.ERROR_MESSAGE);
            } else {
                estudianteLogica.crearEstudiante(estudiante);
                BotonLimpiarEstudianteActionPerformed(evt);
                JOptionPane.showMessageDialog(PanelCompleto, "Se ha registrado el estudiante: " + estudiante.getNombre(), "Registrar Estudiante", JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(Exception e){
        }
    }//GEN-LAST:event_BotonCrearEstudianteActionPerformed

    private void BotonLimpiarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarEstudianteActionPerformed
        TextIdEstudiante.setText(null);
        TextNombeEstudiante.setText(null);
        TextEdadEstudiante.setText(null);
        ComboSexoEstudiante.setSelectedItem(null);
        ComboGradoEstudiante.setSelectedItem(null);
        TextUniformeEstudiante.setText(null);
    }//GEN-LAST:event_BotonLimpiarEstudianteActionPerformed

    private void BotonVisualizarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVisualizarEstudianteActionPerformed
        this.setVisible(false);
        new InterfazCRUDEstudiante().setVisible(true);
    }//GEN-LAST:event_BotonVisualizarEstudianteActionPerformed

    private void ComboSexoEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboSexoEstudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboSexoEstudianteActionPerformed

    private void btnHome4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome4ActionPerformed
        this.setVisible(false);
        new InterfazHomePage().setVisible(true);
    }//GEN-LAST:event_btnHome4ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InterfazCRUDEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InterfazCRUDEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InterfazCRUDEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InterfazCRUDEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new InterfazCRUDEstudiante2().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCrearEstudiante;
    private javax.swing.JButton BotonLimpiarEstudiante;
    private javax.swing.JButton BotonVisualizarEstudiante;
    private javax.swing.JComboBox<String> ComboGradoEstudiante;
    private javax.swing.JComboBox<String> ComboSexoEstudiante;
    private javax.swing.JPanel Datos;
    private javax.swing.JLabel EdadEstudiante;
    private javax.swing.JLabel GradoEstudiante;
    private javax.swing.JLabel IconoEstudiante;
    private javax.swing.JLabel IdEstudiante;
    private javax.swing.JLabel NombreEstudiante;
    private javax.swing.JPanel Operadores;
    private javax.swing.JPanel PanelCompleto;
    private javax.swing.JLabel SexoEstudiante;
    private javax.swing.JTextField TextEdadEstudiante;
    private javax.swing.JLabel TextEstudiante;
    private javax.swing.JTextField TextIdEstudiante;
    private javax.swing.JTextField TextNombeEstudiante;
    private javax.swing.JTextField TextUniformeEstudiante;
    private javax.swing.JLabel TextoCabecera;
    private javax.swing.JLabel UniformeEstudiante;
    private javax.swing.JButton btnHome4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
