/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.usbcali.colegiousb.presentacion;

import co.edu.usbcali.colegiousb.logica.EmpleadoLogica;
import co.edu.usbcali.colegiousb.logica.GradoLogica;
import co.edu.usbcali.colegiousb.logica.IEmpleadoLogica;
import co.edu.usbcali.colegiousb.logica.IGradoLogica;
import co.edu.usbcali.colegiousb.logica.IMateriaLogica;
import co.edu.usbcali.colegiousb.logica.MateriaLogica;
import co.edu.usbcali.colegiousb.modelo.Materia;
import javax.swing.JOptionPane;
/**
 *
 * @author FAVI
 */
public class InterfazCRUDMateria2 extends javax.swing.JFrame {
    private IMateriaLogica materiaLogica = new MateriaLogica();
    private IEmpleadoLogica empleadoLogica = new EmpleadoLogica();
    private IGradoLogica gradoLogica = new GradoLogica();
    
    /**
     * Creates new form InterfazCRUDEstudiante
     */
    
    public InterfazCRUDMateria2() {
        initComponents();
        botonTransparente();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Registrar Materia");
    }
    
    public void botonTransparente(){
        btnHome.setOpaque(false);
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        BotonCrearMateria.setOpaque(false);
        BotonCrearMateria.setBorderPainted(false);
        BotonCrearMateria.setContentAreaFilled(false);
        BotonLimpiarMateria.setOpaque(false);
        BotonLimpiarMateria.setBorderPainted(false);
        BotonLimpiarMateria.setContentAreaFilled(false);
        BotonVisualizarMateria.setOpaque(false);
        BotonVisualizarMateria.setBorderPainted(false);
        BotonVisualizarMateria.setContentAreaFilled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCompleto = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        TextMateria = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        TextoCabecera = new javax.swing.JLabel();
        Datos = new javax.swing.JPanel();
        MateriaId = new javax.swing.JLabel();
        TextIdMateriaMateria = new javax.swing.JTextField();
        EmpleadoMateria = new javax.swing.JLabel();
        TextEmpleadoMateria = new javax.swing.JTextField();
        ContenidoMateria = new javax.swing.JLabel();
        GradoMateria = new javax.swing.JLabel();
        TextHorarioMateria = new javax.swing.JTextField();
        HorarioMateria = new javax.swing.JLabel();
        TextContenidoMateria = new javax.swing.JTextField();
        MateriaId1 = new javax.swing.JLabel();
        TextNombreMateria = new javax.swing.JTextField();
        ComboGrado = new javax.swing.JComboBox<>();
        Operadores = new javax.swing.JPanel();
        BotonCrearMateria = new javax.swing.JButton();
        BotonVisualizarMateria = new javax.swing.JButton();
        BotonLimpiarMateria = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelCompleto.setBackground(new java.awt.Color(79, 134, 193));
        PanelCompleto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(178, 218, 250));

        TextMateria.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TextMateria.setForeground(new java.awt.Color(0, 61, 112));
        TextMateria.setText("Materia");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/cuaderno-cerrado-y-boligrafo.png"))); // NOI18N

        btnHome.setBackground(new java.awt.Color(178, 218, 250));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/back.png"))); // NOI18N
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(TextMateria))
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnHome)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnHome)
                .addGap(121, 121, 121)
                .addComponent(TextMateria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        PanelCompleto.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 530));

        TextoCabecera.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        TextoCabecera.setForeground(new java.awt.Color(255, 255, 255));
        TextoCabecera.setText("Sistema Registro De Materias");
        PanelCompleto.add(TextoCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        Datos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        Datos.setForeground(new java.awt.Color(255, 255, 255));
        Datos.setOpaque(false);

        MateriaId.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MateriaId.setForeground(new java.awt.Color(255, 255, 255));
        MateriaId.setText("Id Materia");

        TextIdMateriaMateria.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        EmpleadoMateria.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        EmpleadoMateria.setForeground(new java.awt.Color(255, 255, 255));
        EmpleadoMateria.setText("Id Docente");

        TextEmpleadoMateria.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        ContenidoMateria.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ContenidoMateria.setForeground(new java.awt.Color(255, 255, 255));
        ContenidoMateria.setText("Contenido");

        GradoMateria.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        GradoMateria.setForeground(new java.awt.Color(255, 255, 255));
        GradoMateria.setText("Grado");

        TextHorarioMateria.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        HorarioMateria.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        HorarioMateria.setForeground(new java.awt.Color(255, 255, 255));
        HorarioMateria.setText("Horario");

        TextContenidoMateria.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        MateriaId1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MateriaId1.setForeground(new java.awt.Color(255, 255, 255));
        MateriaId1.setText("Nombre");

        TextNombreMateria.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        ComboGrado.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ComboGrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11" }));

        javax.swing.GroupLayout DatosLayout = new javax.swing.GroupLayout(Datos);
        Datos.setLayout(DatosLayout);
        DatosLayout.setHorizontalGroup(
            DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GradoMateria)
                    .addComponent(HorarioMateria)
                    .addComponent(EmpleadoMateria)
                    .addComponent(MateriaId)
                    .addComponent(ContenidoMateria)
                    .addComponent(MateriaId1))
                .addGap(44, 44, 44)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextHorarioMateria, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addComponent(TextIdMateriaMateria)
                    .addComponent(TextNombreMateria)
                    .addComponent(TextEmpleadoMateria)
                    .addComponent(TextContenidoMateria, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addComponent(ComboGrado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        DatosLayout.setVerticalGroup(
            DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MateriaId)
                    .addComponent(TextIdMateriaMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MateriaId1))
                .addGap(18, 18, 18)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextEmpleadoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpleadoMateria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextContenidoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ContenidoMateria))
                .addGap(17, 17, 17)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GradoMateria)
                    .addComponent(ComboGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextHorarioMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HorarioMateria))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        PanelCompleto.add(Datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 440, 300));

        Operadores.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Operadores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        Operadores.setOpaque(false);

        BotonCrearMateria.setBackground(new java.awt.Color(178, 218, 250));
        BotonCrearMateria.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BotonCrearMateria.setForeground(new java.awt.Color(0, 61, 112));
        BotonCrearMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/anadir (1).png"))); // NOI18N
        BotonCrearMateria.setText("Crear");
        BotonCrearMateria.setBorderPainted(false);
        BotonCrearMateria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCrearMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCrearMateriaActionPerformed(evt);
            }
        });

        BotonVisualizarMateria.setBackground(new java.awt.Color(178, 218, 250));
        BotonVisualizarMateria.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BotonVisualizarMateria.setForeground(new java.awt.Color(0, 61, 112));
        BotonVisualizarMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/visualizacion-de-datos.png"))); // NOI18N
        BotonVisualizarMateria.setText("Visualizar");
        BotonVisualizarMateria.setBorderPainted(false);
        BotonVisualizarMateria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonVisualizarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVisualizarMateriaActionPerformed(evt);
            }
        });

        BotonLimpiarMateria.setBackground(new java.awt.Color(178, 218, 250));
        BotonLimpiarMateria.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BotonLimpiarMateria.setForeground(new java.awt.Color(0, 61, 112));
        BotonLimpiarMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/limpieza-de-datos (1).png"))); // NOI18N
        BotonLimpiarMateria.setText("Limpiar");
        BotonLimpiarMateria.setBorderPainted(false);
        BotonLimpiarMateria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonLimpiarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarMateriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OperadoresLayout = new javax.swing.GroupLayout(Operadores);
        Operadores.setLayout(OperadoresLayout);
        OperadoresLayout.setHorizontalGroup(
            OperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OperadoresLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(BotonCrearMateria)
                .addGap(18, 18, 18)
                .addComponent(BotonVisualizarMateria)
                .addGap(18, 18, 18)
                .addComponent(BotonLimpiarMateria)
                .addGap(22, 22, 22))
        );
        OperadoresLayout.setVerticalGroup(
            OperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperadoresLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(OperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonCrearMateria)
                    .addComponent(BotonVisualizarMateria)
                    .addComponent(BotonLimpiarMateria))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        PanelCompleto.add(Operadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 440, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCrearMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCrearMateriaActionPerformed
        try {
            Materia materia = new Materia();
            materia.setId(TextIdMateriaMateria.getText());
            materia.setNombre(TextNombreMateria.getText());
            materia.setDocente(empleadoLogica.obtenerEmpleadoPorId(TextEmpleadoMateria.getText()));
            materia.setContenido(TextContenidoMateria.getText());
            materia.setGrado(gradoLogica.obtenerGradoPorId(Integer.parseInt(ComboGrado.getSelectedItem().toString())));
            materia.setHorario(TextHorarioMateria.getText());
        
            if (empleadoLogica.obtenerEmpleadoPorId(TextEmpleadoMateria.getText()) == null) {
                JOptionPane.showMessageDialog(PanelCompleto, "El id del docente no existe", "Registrar Materia", JOptionPane.ERROR_MESSAGE);
            }
            
            if (TextIdMateriaMateria.getText().isEmpty() || TextNombreMateria.getText().isEmpty() || TextEmpleadoMateria.getText().isEmpty() || TextContenidoMateria.getText().isEmpty() || TextHorarioMateria.getText().isEmpty()) {
                JOptionPane.showMessageDialog(PanelCompleto, "Todos los campos son obligatorios", "Registrar Materia", JOptionPane.ERROR_MESSAGE);
            }
            
            if (materiaLogica.validarMateriaId(materia.getId())) {
                JOptionPane.showMessageDialog(PanelCompleto, "El Id debe ser único e irrepetible", "Registrar Materia", JOptionPane.ERROR_MESSAGE);
            } else if (!materiaLogica.validarDocenteMateria(TextEmpleadoMateria.getText())) {
                JOptionPane.showMessageDialog(PanelCompleto, "No se puede asignar un empleado que no sea docente a una materia", "Registrar Materia", JOptionPane.ERROR_MESSAGE);
            } else {
                materiaLogica.crearMateria(materia);
                BotonLimpiarMateriaActionPerformed(evt);
                JOptionPane.showMessageDialog(PanelCompleto, "Se ha registrado la materia: " + materia.getNombre(), "Registrar Materia", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_BotonCrearMateriaActionPerformed

    private void BotonVisualizarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVisualizarMateriaActionPerformed
        this.setVisible(false);
        new InterfazCRUDMateria().setVisible(true);
    }//GEN-LAST:event_BotonVisualizarMateriaActionPerformed

    private void BotonLimpiarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarMateriaActionPerformed
        TextIdMateriaMateria.setText(null);
        TextNombreMateria.setText(null);
        TextEmpleadoMateria.setText(null);
        TextContenidoMateria.setText(null);
        TextHorarioMateria.setText(null);
        ComboGrado.setSelectedItem(null);
    }//GEN-LAST:event_BotonLimpiarMateriaActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        this.setVisible(false);
        new InterfazHomePage().setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InterfazCRUDEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InterfazCRUDEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InterfazCRUDEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InterfazCRUDEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new InterfazCRUDMateria2().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCrearMateria;
    private javax.swing.JButton BotonLimpiarMateria;
    private javax.swing.JButton BotonVisualizarMateria;
    private javax.swing.JComboBox<String> ComboGrado;
    private javax.swing.JLabel ContenidoMateria;
    private javax.swing.JPanel Datos;
    private javax.swing.JLabel EmpleadoMateria;
    private javax.swing.JLabel GradoMateria;
    private javax.swing.JLabel HorarioMateria;
    private javax.swing.JLabel MateriaId;
    private javax.swing.JLabel MateriaId1;
    private javax.swing.JPanel Operadores;
    private javax.swing.JPanel PanelCompleto;
    private javax.swing.JTextField TextContenidoMateria;
    private javax.swing.JTextField TextEmpleadoMateria;
    private javax.swing.JTextField TextHorarioMateria;
    private javax.swing.JTextField TextIdMateriaMateria;
    private javax.swing.JLabel TextMateria;
    private javax.swing.JTextField TextNombreMateria;
    private javax.swing.JLabel TextoCabecera;
    private javax.swing.JButton btnHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
