/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.usbcali.colegiousb.presentacion;

import co.edu.usbcali.colegiousb.logica.IMateriaEstudianteLogica;
import co.edu.usbcali.colegiousb.logica.MateriaEstudianteLogica;
import co.edu.usbcali.colegiousb.modelo.MateriaEstudiante;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author FAVI
 */
public class InterfazCRUDMateriaEstudiante extends javax.swing.JFrame {
    private IMateriaEstudianteLogica materiaEstudianteLogica = new MateriaEstudianteLogica();
    
    /**
     * Creates new form InterfazCRUDEstudiante
     */
    
    public InterfazCRUDMateriaEstudiante() {
        initComponents();
        cargarMateriaEstudiante();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Visualizar Materia");
    }

    public final void cargarMateriaEstudiante(){
        try{
            List<MateriaEstudiante> materiasEstudiantes =  materiaEstudianteLogica.visualizarMateriaEstudiante();
            DefaultListModel listModel = new DefaultListModel();
            
            for(MateriaEstudiante materiaEstudiante : materiasEstudiantes){
                listModel.addElement("Id Materia: " + materiaEstudiante.getMateria().getId() + ", Materia: " + materiaEstudiante.getMateria().getNombre() + ", Id Estudiante: " + materiaEstudiante.getEstudiante().getId() + ", Estudiante: " + materiaEstudiante.getEstudiante().getNombre());
            }
            
            lstMateriaEstudiante.setModel(listModel);
        }catch(Exception e){
            JOptionPane.showMessageDialog(PanelCompleto, e.getMessage(), "Visualizar MateriaEstudiante", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCompleto = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        TextMateria = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TextoCabecera = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstMateriaEstudiante = new javax.swing.JList<>();
        TextoCabecera1 = new javax.swing.JLabel();
        BotonRegresarActividad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelCompleto.setBackground(new java.awt.Color(79, 134, 193));
        PanelCompleto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(178, 218, 250));

        TextMateria.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TextMateria.setForeground(new java.awt.Color(0, 61, 112));
        TextMateria.setText("Materia");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/cuaderno-cerrado-y-boligrafo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(TextMateria))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(TextMateria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        PanelCompleto.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 530));

        TextoCabecera.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        TextoCabecera.setForeground(new java.awt.Color(255, 255, 255));
        TextoCabecera.setText("Sistema Registro De Materias");
        PanelCompleto.add(TextoCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Registro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setOpaque(false);

        lstMateriaEstudiante.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(lstMateriaEstudiante);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        PanelCompleto.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 480, 360));

        TextoCabecera1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        TextoCabecera1.setForeground(new java.awt.Color(255, 255, 255));
        TextoCabecera1.setText("Por Estudiantes");
        PanelCompleto.add(TextoCabecera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        BotonRegresarActividad.setBackground(new java.awt.Color(178, 218, 250));
        BotonRegresarActividad.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BotonRegresarActividad.setForeground(new java.awt.Color(0, 61, 112));
        BotonRegresarActividad.setText("Regresar");
        BotonRegresarActividad.setBorderPainted(false);
        BotonRegresarActividad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRegresarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresarActividadActionPerformed(evt);
            }
        });
        PanelCompleto.add(BotonRegresarActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegresarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresarActividadActionPerformed
        this.setVisible(false);
        new InterfazCRUDMateriaEstudiante2().setVisible(true);
    }//GEN-LAST:event_BotonRegresarActividadActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InterfazCRUDMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InterfazCRUDMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InterfazCRUDMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InterfazCRUDMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new InterfazCRUDMateria().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRegresarActividad;
    private javax.swing.JPanel PanelCompleto;
    private javax.swing.JLabel TextMateria;
    private javax.swing.JLabel TextoCabecera;
    private javax.swing.JLabel TextoCabecera1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstMateriaEstudiante;
    // End of variables declaration//GEN-END:variables
}
