/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.usbcali.colegiousb.presentacion;

import co.edu.usbcali.colegiousb.logica.EstudianteLogica;
import co.edu.usbcali.colegiousb.logica.IEstudianteLogica;
import co.edu.usbcali.colegiousb.logica.IMateriaEstudianteLogica;
import co.edu.usbcali.colegiousb.logica.IMateriaLogica;
import co.edu.usbcali.colegiousb.logica.MateriaEstudianteLogica;
import co.edu.usbcali.colegiousb.logica.MateriaLogica;
import co.edu.usbcali.colegiousb.modelo.MateriaEstudiante;
import javax.swing.JOptionPane;
/**
 *
 * @author FAVI
 */
public class InterfazCRUDMateriaEstudiante2 extends javax.swing.JFrame {
    private IMateriaEstudianteLogica materiaEstudianteLogica = new MateriaEstudianteLogica();
    private IMateriaLogica materiaLogica = new MateriaLogica();
    private IEstudianteLogica estudianteLogica = new EstudianteLogica();
    
    /**
     * Creates new form InterfazCRUDEstudiante
     */
    
    public InterfazCRUDMateriaEstudiante2() {
        initComponents();
        botonTransparente();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Registrar Materia");
    }
    
    public void botonTransparente(){
        btnHome4.setOpaque(false);
        btnHome4.setBorderPainted(false);
        btnHome4.setContentAreaFilled(false);
        BotonCrearMateria.setOpaque(false);
        BotonCrearMateria.setBorderPainted(false);
        BotonCrearMateria.setContentAreaFilled(false);
        BotonLimpiarMateria.setOpaque(false);
        BotonLimpiarMateria.setBorderPainted(false);
        BotonLimpiarMateria.setContentAreaFilled(false);
        BotonVisualizarMateria.setOpaque(false);
        BotonVisualizarMateria.setBorderPainted(false);
        BotonVisualizarMateria.setContentAreaFilled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCompleto = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        TextMateria = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnHome4 = new javax.swing.JButton();
        TextoCabecera = new javax.swing.JLabel();
        Datos = new javax.swing.JPanel();
        IdMateria = new javax.swing.JLabel();
        TextIdMateriaMateriaEstudiante = new javax.swing.JTextField();
        EstudianteMateria = new javax.swing.JLabel();
        TextEstudianteMateriaEstudiante = new javax.swing.JTextField();
        Operadores = new javax.swing.JPanel();
        BotonCrearMateria = new javax.swing.JButton();
        BotonVisualizarMateria = new javax.swing.JButton();
        BotonLimpiarMateria = new javax.swing.JButton();
        TextoCabecera1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelCompleto.setBackground(new java.awt.Color(79, 134, 193));
        PanelCompleto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(178, 218, 250));

        TextMateria.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TextMateria.setForeground(new java.awt.Color(0, 61, 112));
        TextMateria.setText("Registro Estudiante");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/registrarse.png"))); // NOI18N

        btnHome4.setBackground(new java.awt.Color(178, 218, 250));
        btnHome4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/back.png"))); // NOI18N
        btnHome4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(TextMateria))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnHome4)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnHome4)
                .addGap(128, 128, 128)
                .addComponent(TextMateria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        PanelCompleto.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 530));

        TextoCabecera.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        TextoCabecera.setForeground(new java.awt.Color(255, 255, 255));
        TextoCabecera.setText("Por Estudiantes");
        PanelCompleto.add(TextoCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        Datos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        Datos.setForeground(new java.awt.Color(255, 255, 255));
        Datos.setOpaque(false);

        IdMateria.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        IdMateria.setForeground(new java.awt.Color(255, 255, 255));
        IdMateria.setText("Id Materia");

        TextIdMateriaMateriaEstudiante.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        EstudianteMateria.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        EstudianteMateria.setForeground(new java.awt.Color(255, 255, 255));
        EstudianteMateria.setText("Id Estudiante ");

        TextEstudianteMateriaEstudiante.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout DatosLayout = new javax.swing.GroupLayout(Datos);
        Datos.setLayout(DatosLayout);
        DatosLayout.setHorizontalGroup(
            DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IdMateria)
                    .addComponent(EstudianteMateria))
                .addGap(18, 18, 18)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextIdMateriaMateriaEstudiante)
                    .addComponent(TextEstudianteMateriaEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        DatosLayout.setVerticalGroup(
            DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdMateria)
                    .addComponent(TextIdMateriaMateriaEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EstudianteMateria)
                    .addComponent(TextEstudianteMateriaEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        PanelCompleto.add(Datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 440, 150));

        Operadores.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Operadores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        Operadores.setOpaque(false);

        BotonCrearMateria.setBackground(new java.awt.Color(178, 218, 250));
        BotonCrearMateria.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BotonCrearMateria.setForeground(new java.awt.Color(0, 61, 112));
        BotonCrearMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/anadir (1).png"))); // NOI18N
        BotonCrearMateria.setText("Crear");
        BotonCrearMateria.setBorderPainted(false);
        BotonCrearMateria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCrearMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCrearMateriaActionPerformed(evt);
            }
        });

        BotonVisualizarMateria.setBackground(new java.awt.Color(178, 218, 250));
        BotonVisualizarMateria.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BotonVisualizarMateria.setForeground(new java.awt.Color(0, 61, 112));
        BotonVisualizarMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/visualizacion-de-datos.png"))); // NOI18N
        BotonVisualizarMateria.setText("Visualizar");
        BotonVisualizarMateria.setBorderPainted(false);
        BotonVisualizarMateria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonVisualizarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVisualizarMateriaActionPerformed(evt);
            }
        });

        BotonLimpiarMateria.setBackground(new java.awt.Color(178, 218, 250));
        BotonLimpiarMateria.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BotonLimpiarMateria.setForeground(new java.awt.Color(0, 61, 112));
        BotonLimpiarMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/limpieza-de-datos (1).png"))); // NOI18N
        BotonLimpiarMateria.setText("Limpiar");
        BotonLimpiarMateria.setBorderPainted(false);
        BotonLimpiarMateria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonLimpiarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarMateriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OperadoresLayout = new javax.swing.GroupLayout(Operadores);
        Operadores.setLayout(OperadoresLayout);
        OperadoresLayout.setHorizontalGroup(
            OperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperadoresLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(BotonCrearMateria)
                .addGap(18, 18, 18)
                .addComponent(BotonVisualizarMateria)
                .addGap(18, 18, 18)
                .addComponent(BotonLimpiarMateria)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        OperadoresLayout.setVerticalGroup(
            OperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperadoresLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(OperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonCrearMateria)
                    .addComponent(BotonVisualizarMateria)
                    .addComponent(BotonLimpiarMateria))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        PanelCompleto.add(Operadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 440, 110));

        TextoCabecera1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        TextoCabecera1.setForeground(new java.awt.Color(255, 255, 255));
        TextoCabecera1.setText("Sistema Registro De Materias");
        PanelCompleto.add(TextoCabecera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCrearMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCrearMateriaActionPerformed
        try{
            MateriaEstudiante materiaEstudiante = new MateriaEstudiante();
            materiaEstudiante.setMateria(materiaLogica.obtenerMateriaPorId(TextIdMateriaMateriaEstudiante.getText()));
            materiaEstudiante.setEstudiante(estudianteLogica.obtenerEstudiantePorId(TextEstudianteMateriaEstudiante.getText()));
            
            if (materiaLogica.obtenerMateriaPorId(TextIdMateriaMateriaEstudiante.getText()) == null) {
                JOptionPane.showMessageDialog(PanelCompleto, "El id de la materia no existe", "Registrar MateriaEstudiante", JOptionPane.ERROR_MESSAGE);
            }
            
            if (estudianteLogica.obtenerEstudiantePorId(TextEstudianteMateriaEstudiante.getText()) == null) {
                JOptionPane.showMessageDialog(PanelCompleto, "El id del estudiante no existe", "Registrar MateriaEstudiante", JOptionPane.ERROR_MESSAGE);
            }
            
            if (TextEstudianteMateriaEstudiante.getText().isEmpty() || TextIdMateriaMateriaEstudiante.getText().isEmpty()) {
                JOptionPane.showMessageDialog(PanelCompleto, "Todos los campos son obligatorios", "Registrar MateriaEstudiante", JOptionPane.ERROR_MESSAGE);
            }
            
            if (materiaEstudiante.getMateria().getGrado().getId() == materiaEstudiante.getEstudiante().getGrado().getId()) {
                materiaEstudianteLogica.crearMateriaEstudiante(materiaEstudiante);
                BotonLimpiarMateriaActionPerformed(evt);
                JOptionPane.showMessageDialog(PanelCompleto, "Se ha regristado correctamente el estudiante: " + materiaEstudiante.getEstudiante().getNombre() + " a la materia: " + materiaEstudiante.getMateria().getNombre(), "Registrar MateriaEstudiante", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(PanelCompleto, "El grado de la materia debe ser el mismo del estudiante", "Registrar MateriaEstudiante", JOptionPane.ERROR_MESSAGE);
            } 
        }catch(Exception e){
        }
    }//GEN-LAST:event_BotonCrearMateriaActionPerformed

    private void btnHome4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome4ActionPerformed
        this.setVisible(false);
        new InterfazHomePage().setVisible(true);
    }//GEN-LAST:event_btnHome4ActionPerformed

    private void BotonLimpiarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarMateriaActionPerformed
        TextEstudianteMateriaEstudiante.setText(null);
        TextIdMateriaMateriaEstudiante.setText(null);
    }//GEN-LAST:event_BotonLimpiarMateriaActionPerformed

    private void BotonVisualizarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVisualizarMateriaActionPerformed
        this.setVisible(false);
        new InterfazCRUDMateriaEstudiante().setVisible(true);
    }//GEN-LAST:event_BotonVisualizarMateriaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InterfazCRUDEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InterfazCRUDEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InterfazCRUDEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InterfazCRUDEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new InterfazCRUDMateria2().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCrearMateria;
    private javax.swing.JButton BotonLimpiarMateria;
    private javax.swing.JButton BotonVisualizarMateria;
    private javax.swing.JPanel Datos;
    private javax.swing.JLabel EstudianteMateria;
    private javax.swing.JLabel IdMateria;
    private javax.swing.JPanel Operadores;
    private javax.swing.JPanel PanelCompleto;
    private javax.swing.JTextField TextEstudianteMateriaEstudiante;
    private javax.swing.JTextField TextIdMateriaMateriaEstudiante;
    private javax.swing.JLabel TextMateria;
    private javax.swing.JLabel TextoCabecera;
    private javax.swing.JLabel TextoCabecera1;
    private javax.swing.JButton btnHome4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
