/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.usbcali.colegiousb.presentacion;

import co.edu.usbcali.colegiousb.logica.EventoLogica;
import co.edu.usbcali.colegiousb.logica.IEventoLogica;
import co.edu.usbcali.colegiousb.modelo.Evento;
import javax.swing.JOptionPane;
/**
/**
 *
 * @author FAVI
 */
public class InterfazCRUDEvento2 extends javax.swing.JFrame {
    private IEventoLogica eventoLogica = new EventoLogica();
    
    /**
     * Creates new form InterfazCRUDEstudiante
     */
    
    public InterfazCRUDEvento2() {
        initComponents();
        botonTransparente();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Registrar Evento");
    }
    
    public void botonTransparente(){
        btnHome4.setOpaque(false);
        btnHome4.setBorderPainted(false);
        btnHome4.setContentAreaFilled(false);
        BotonCrearEvento.setOpaque(false);
        BotonCrearEvento.setBorderPainted(false);
        BotonCrearEvento.setContentAreaFilled(false);
        BotonLimpiarEvento.setOpaque(false);
        BotonLimpiarEvento.setBorderPainted(false);
        BotonLimpiarEvento.setContentAreaFilled(false);
        BotonVisualizarEvento.setOpaque(false);
        BotonVisualizarEvento.setBorderPainted(false);
        BotonVisualizarEvento.setContentAreaFilled(false);
    }
    
        //Método para crear el Archivo de registro o nuestra BD
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCompleto = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        TextEvento = new javax.swing.JLabel();
        IconoEvento = new javax.swing.JLabel();
        btnHome4 = new javax.swing.JButton();
        TextoCabecera = new javax.swing.JLabel();
        Datos = new javax.swing.JPanel();
        EventoEvento = new javax.swing.JLabel();
        MateriaEvento = new javax.swing.JLabel();
        TextIdEvento = new javax.swing.JTextField();
        UbicacionEvento = new javax.swing.JLabel();
        TextUbicacionEvento = new javax.swing.JTextField();
        DuracionEvento = new javax.swing.JLabel();
        ComboEventoEvento = new javax.swing.JComboBox<>();
        TextDuracionEvento = new javax.swing.JTextField();
        Operadores = new javax.swing.JPanel();
        BotonCrearEvento = new javax.swing.JButton();
        BotonVisualizarEvento = new javax.swing.JButton();
        BotonLimpiarEvento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelCompleto.setBackground(new java.awt.Color(79, 134, 193));
        PanelCompleto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(178, 218, 250));

        TextEvento.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TextEvento.setForeground(new java.awt.Color(0, 61, 112));
        TextEvento.setText("Evento");

        IconoEvento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/calendario.png"))); // NOI18N

        btnHome4.setBackground(new java.awt.Color(178, 218, 250));
        btnHome4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/back.png"))); // NOI18N
        btnHome4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(TextEvento))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(IconoEvento))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnHome4)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnHome4)
                .addGap(132, 132, 132)
                .addComponent(TextEvento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IconoEvento)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        PanelCompleto.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 530));

        TextoCabecera.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        TextoCabecera.setForeground(new java.awt.Color(255, 255, 255));
        TextoCabecera.setText("Sistema Registro De Eventos");
        PanelCompleto.add(TextoCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        Datos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        Datos.setForeground(new java.awt.Color(255, 255, 255));
        Datos.setOpaque(false);

        EventoEvento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        EventoEvento.setForeground(new java.awt.Color(255, 255, 255));
        EventoEvento.setText("Evento");

        MateriaEvento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MateriaEvento.setForeground(new java.awt.Color(255, 255, 255));
        MateriaEvento.setText("Id Evento");

        TextIdEvento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        UbicacionEvento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UbicacionEvento.setForeground(new java.awt.Color(255, 255, 255));
        UbicacionEvento.setText("Ubicación");

        TextUbicacionEvento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        DuracionEvento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        DuracionEvento.setForeground(new java.awt.Color(255, 255, 255));
        DuracionEvento.setText("Duración");

        ComboEventoEvento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ComboEventoEvento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kermes", "Izada de Bandera", "Semana Cultural", "Festividad" }));

        TextDuracionEvento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout DatosLayout = new javax.swing.GroupLayout(Datos);
        Datos.setLayout(DatosLayout);
        DatosLayout.setHorizontalGroup(
            DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatosLayout.createSequentialGroup()
                        .addComponent(MateriaEvento)
                        .addGap(73, 73, 73)
                        .addComponent(TextIdEvento, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                    .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(DatosLayout.createSequentialGroup()
                            .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(UbicacionEvento)
                                .addComponent(DuracionEvento))
                            .addGap(74, 74, 74)
                            .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TextUbicacionEvento, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                                .addComponent(TextDuracionEvento)))
                        .addGroup(DatosLayout.createSequentialGroup()
                            .addComponent(EventoEvento)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                            .addComponent(ComboEventoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        DatosLayout.setVerticalGroup(
            DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MateriaEvento)
                    .addComponent(TextIdEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EventoEvento)
                    .addComponent(ComboEventoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UbicacionEvento)
                    .addComponent(TextUbicacionEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DuracionEvento)
                    .addComponent(TextDuracionEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        PanelCompleto.add(Datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 440, 220));

        Operadores.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Operadores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        Operadores.setOpaque(false);

        BotonCrearEvento.setBackground(new java.awt.Color(178, 218, 250));
        BotonCrearEvento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BotonCrearEvento.setForeground(new java.awt.Color(0, 61, 112));
        BotonCrearEvento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/anadir (1).png"))); // NOI18N
        BotonCrearEvento.setText("Crear");
        BotonCrearEvento.setBorderPainted(false);
        BotonCrearEvento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCrearEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCrearEventoActionPerformed(evt);
            }
        });

        BotonVisualizarEvento.setBackground(new java.awt.Color(178, 218, 250));
        BotonVisualizarEvento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BotonVisualizarEvento.setForeground(new java.awt.Color(0, 61, 112));
        BotonVisualizarEvento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/visualizacion-de-datos.png"))); // NOI18N
        BotonVisualizarEvento.setText("Visualizar");
        BotonVisualizarEvento.setBorderPainted(false);
        BotonVisualizarEvento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonVisualizarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVisualizarEventoActionPerformed(evt);
            }
        });

        BotonLimpiarEvento.setBackground(new java.awt.Color(178, 218, 250));
        BotonLimpiarEvento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BotonLimpiarEvento.setForeground(new java.awt.Color(0, 61, 112));
        BotonLimpiarEvento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/limpieza-de-datos (1).png"))); // NOI18N
        BotonLimpiarEvento.setText("Limpiar");
        BotonLimpiarEvento.setBorderPainted(false);
        BotonLimpiarEvento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonLimpiarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarEventoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OperadoresLayout = new javax.swing.GroupLayout(Operadores);
        Operadores.setLayout(OperadoresLayout);
        OperadoresLayout.setHorizontalGroup(
            OperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperadoresLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(BotonCrearEvento)
                .addGap(18, 18, 18)
                .addComponent(BotonVisualizarEvento)
                .addGap(18, 18, 18)
                .addComponent(BotonLimpiarEvento)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        OperadoresLayout.setVerticalGroup(
            OperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonCrearEvento)
                    .addComponent(BotonVisualizarEvento)
                    .addComponent(BotonLimpiarEvento))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        PanelCompleto.add(Operadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 440, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCrearEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCrearEventoActionPerformed
        try {
            Evento evento = new Evento();
            evento.setId(TextIdEvento.getText());
            evento.setEvento(ComboEventoEvento.getSelectedItem().toString());
            evento.setDuracion(TextDuracionEvento.getText());
            evento.setUbicacion(TextUbicacionEvento.getText());
        
            if (TextIdEvento.getText().isEmpty() || TextDuracionEvento.getText().isEmpty() || TextUbicacionEvento.getText().isEmpty()) {
                JOptionPane.showMessageDialog(PanelCompleto, "Todos los campos son obligatorios", "Registrar Evento", JOptionPane.ERROR_MESSAGE);
            }
            
            if (eventoLogica.validarEventoId(evento.getId())) {
                JOptionPane.showMessageDialog(PanelCompleto, "El Id debe ser único e irrepetible", "Registrar Evento", JOptionPane.ERROR_MESSAGE);
            } else {
                eventoLogica.crearEvento(evento);
                BotonLimpiarEventoActionPerformed(evt);
                JOptionPane.showMessageDialog(PanelCompleto, "Se ha registrado el evento: " + evento.getEvento(), "Registrar Evento", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_BotonCrearEventoActionPerformed

    private void BotonLimpiarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarEventoActionPerformed
        TextIdEvento.setText(null);
        TextDuracionEvento.setText(null);
        TextUbicacionEvento.setText(null);
        ComboEventoEvento.setSelectedItem(null);
    }//GEN-LAST:event_BotonLimpiarEventoActionPerformed

    private void BotonVisualizarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVisualizarEventoActionPerformed
        this.setVisible(false);
        new InterfazCRUDEvento().setVisible(true);
    }//GEN-LAST:event_BotonVisualizarEventoActionPerformed

    private void btnHome4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome4ActionPerformed
        this.setVisible(false);
        new InterfazHomePage().setVisible(true);
    }//GEN-LAST:event_btnHome4ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InterfazCRUDEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InterfazCRUDEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InterfazCRUDEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InterfazCRUDEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new InterfazCRUDEvento2().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCrearEvento;
    private javax.swing.JButton BotonLimpiarEvento;
    private javax.swing.JButton BotonVisualizarEvento;
    private javax.swing.JComboBox<String> ComboEventoEvento;
    private javax.swing.JPanel Datos;
    private javax.swing.JLabel DuracionEvento;
    private javax.swing.JLabel EventoEvento;
    private javax.swing.JLabel IconoEvento;
    private javax.swing.JLabel MateriaEvento;
    private javax.swing.JPanel Operadores;
    private javax.swing.JPanel PanelCompleto;
    private javax.swing.JTextField TextDuracionEvento;
    private javax.swing.JLabel TextEvento;
    private javax.swing.JTextField TextIdEvento;
    private javax.swing.JTextField TextUbicacionEvento;
    private javax.swing.JLabel TextoCabecera;
    private javax.swing.JLabel UbicacionEvento;
    private javax.swing.JButton btnHome4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
