/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.usbcali.colegiousb.presentacion;

import co.edu.usbcali.colegiousb.logica.IUsuarioLogica;
import co.edu.usbcali.colegiousb.logica.UsuarioLogica;
import javax.swing.JOptionPane;
/**
 *
 * @author FAVI
 */
public class InterfazLoginAdministrador extends javax.swing.JFrame {
    private IUsuarioLogica usuarioLogica = new UsuarioLogica();
 
    /**
     * Creates new form InterfazLogin
     */
    
    public InterfazLoginAdministrador() {
        initComponents();
        botonTransparente();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Iniciar Sesión");
    }

    public void botonTransparente(){
        btnRegistrar.setOpaque(false);
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.setContentAreaFilled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MedioPanel = new javax.swing.JPanel();
        ColegioUSB = new javax.swing.JTextField();
        IconoColegio = new javax.swing.JLabel();
        AbajoPanel = new javax.swing.JPanel();
        Usuario = new javax.swing.JLabel();
        Contraseña = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        TextUsuarioLogin = new javax.swing.JTextField();
        IconoInicioSesion = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        txtUsuarioContrasena = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MedioPanel.setBackground(new java.awt.Color(80, 134, 193));
        MedioPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ColegioUSB.setEditable(false);
        ColegioUSB.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        ColegioUSB.setForeground(new java.awt.Color(80, 134, 193));
        ColegioUSB.setText("ColegioUSB");
        ColegioUSB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColegioUSBActionPerformed(evt);
            }
        });

        IconoColegio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/icons8-school-building-100(1).png"))); // NOI18N

        javax.swing.GroupLayout MedioPanelLayout = new javax.swing.GroupLayout(MedioPanel);
        MedioPanel.setLayout(MedioPanelLayout);
        MedioPanelLayout.setHorizontalGroup(
            MedioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MedioPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(MedioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MedioPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(IconoColegio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ColegioUSB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        MedioPanelLayout.setVerticalGroup(
            MedioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MedioPanelLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(IconoColegio, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ColegioUSB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Usuario.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Usuario.setText("Usuario");

        Contraseña.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Contraseña.setText("Contraseña");

        btnIniciarSesion.setBackground(new java.awt.Color(0, 61, 112));
        btnIniciarSesion.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        TextUsuarioLogin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        IconoInicioSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/usuario.png"))); // NOI18N

        btnRegistrar.setBackground(new java.awt.Color(0, 61, 112));
        btnRegistrar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 61, 112));
        btnRegistrar.setText("¿No tienes cuenta? Regístrate");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        txtUsuarioContrasena.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtUsuarioContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioContrasenaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AbajoPanelLayout = new javax.swing.GroupLayout(AbajoPanel);
        AbajoPanel.setLayout(AbajoPanelLayout);
        AbajoPanelLayout.setHorizontalGroup(
            AbajoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbajoPanelLayout.createSequentialGroup()
                .addGroup(AbajoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbajoPanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AbajoPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(AbajoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRegistrar)
                            .addGroup(AbajoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Usuario)
                                .addComponent(Contraseña)
                                .addComponent(TextUsuarioLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                                .addComponent(txtUsuarioContrasena)))))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(AbajoPanelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(IconoInicioSesion)
                .addGap(0, 85, Short.MAX_VALUE))
        );
        AbajoPanelLayout.setVerticalGroup(
            AbajoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbajoPanelLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(IconoInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Usuario)
                .addGap(18, 18, 18)
                .addComponent(TextUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Contraseña)
                .addGap(18, 18, 18)
                .addComponent(txtUsuarioContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrar)
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MedioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AbajoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MedioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AbajoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        try {
            if (usuarioLogica.validarUsuario(TextUsuarioLogin.getText(), txtUsuarioContrasena.getText())) {
                JOptionPane.showMessageDialog(AbajoPanel, "Ingresaste con exito", "Iniciar Sesión", JOptionPane.INFORMATION_MESSAGE);

                this.setVisible(false);
                new InterfazHomePage().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(AbajoPanel, "Usuario y/o contraseña incorrectos", "Iniciar Sesión", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        this.setVisible(false);
        new InterfazRegistrarAdministrador().setVisible(true);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtUsuarioContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioContrasenaActionPerformed

    private void ColegioUSBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColegioUSBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColegioUSBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazLoginAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazLoginAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazLoginAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazLoginAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazLoginAdministrador().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AbajoPanel;
    private javax.swing.JTextField ColegioUSB;
    private javax.swing.JLabel Contraseña;
    private javax.swing.JLabel IconoColegio;
    private javax.swing.JLabel IconoInicioSesion;
    private javax.swing.JPanel MedioPanel;
    private javax.swing.JTextField TextUsuarioLogin;
    private javax.swing.JLabel Usuario;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JPasswordField txtUsuarioContrasena;
    // End of variables declaration//GEN-END:variables
}
