/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.usbcali.colegiousb.presentacion;

import co.edu.usbcali.colegiousb.logica.IUsuarioLogica;
import co.edu.usbcali.colegiousb.logica.UsuarioLogica;
import co.edu.usbcali.colegiousb.modelo.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author FAVI
 */
public class InterfazRegistrarAdministrador extends javax.swing.JFrame {
    private IUsuarioLogica usuarioLogica = new UsuarioLogica();
            
    /**
     * Creates new form InterfazLogin
     */
    public InterfazRegistrarAdministrador() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Registar Administrador");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MedioPanel = new javax.swing.JPanel();
        Usuario = new javax.swing.JLabel();
        Contraseña = new javax.swing.JLabel();
        IniciarSesion = new javax.swing.JButton();
        TextUsuario = new javax.swing.JTextField();
        IconoRegistro = new javax.swing.JLabel();
        TextContrasena = new javax.swing.JPasswordField();
        AbajoPanel = new javax.swing.JPanel();
        Registro = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 500), new java.awt.Dimension(0, 500), new java.awt.Dimension(32767, 500));
        Nombre = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        UsuarioRegistro = new javax.swing.JLabel();
        ContraseñaRegistro = new javax.swing.JLabel();
        BotonRegistro = new javax.swing.JButton();
        TextNombreRegistro = new javax.swing.JTextField();
        TextUsuarioRegistro = new javax.swing.JTextField();
        TextApellidoRegistro = new javax.swing.JTextField();
        TextEmailRegistro = new javax.swing.JTextField();
        TextContrasenaRegistro = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MedioPanel.setBackground(new java.awt.Color(80, 134, 193));
        MedioPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Usuario.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Usuario.setText("Usuario");

        Contraseña.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        Contraseña.setText("Contraseña");

        IniciarSesion.setBackground(new java.awt.Color(0, 61, 112));
        IniciarSesion.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        IniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        IniciarSesion.setText("Iniciar Sesión");
        IniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesionActionPerformed(evt);
            }
        });

        TextUsuario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        IconoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/usuario1.png"))); // NOI18N

        TextContrasena.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout MedioPanelLayout = new javax.swing.GroupLayout(MedioPanel);
        MedioPanel.setLayout(MedioPanelLayout);
        MedioPanelLayout.setHorizontalGroup(
            MedioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MedioPanelLayout.createSequentialGroup()
                .addGroup(MedioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MedioPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(MedioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Contraseña)
                            .addComponent(Usuario)
                            .addComponent(TextUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addGroup(MedioPanelLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(IconoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TextContrasena)))
                    .addGroup(MedioPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(IniciarSesion)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        MedioPanelLayout.setVerticalGroup(
            MedioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MedioPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(IconoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Contraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(IniciarSesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Registro.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        Registro.setForeground(new java.awt.Color(0, 61, 112));
        Registro.setText("Registro");

        Nombre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Nombre.setText("Nombre");

        Apellido.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Apellido.setText("Apellido");

        Email.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Email.setText("Email");

        UsuarioRegistro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        UsuarioRegistro.setText("Usuario");

        ContraseñaRegistro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ContraseñaRegistro.setText("Contraseña");

        BotonRegistro.setBackground(new java.awt.Color(0, 61, 112));
        BotonRegistro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BotonRegistro.setForeground(new java.awt.Color(255, 255, 255));
        BotonRegistro.setText("Registrar");
        BotonRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistroActionPerformed(evt);
            }
        });

        TextNombreRegistro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TextNombreRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNombreRegistroActionPerformed(evt);
            }
        });

        TextUsuarioRegistro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TextUsuarioRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextUsuarioRegistroActionPerformed(evt);
            }
        });

        TextApellidoRegistro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        TextEmailRegistro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        TextContrasenaRegistro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        javax.swing.GroupLayout AbajoPanelLayout = new javax.swing.GroupLayout(AbajoPanel);
        AbajoPanel.setLayout(AbajoPanelLayout);
        AbajoPanelLayout.setHorizontalGroup(
            AbajoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbajoPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(AbajoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbajoPanelLayout.createSequentialGroup()
                        .addGroup(AbajoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Apellido)
                            .addComponent(Nombre)
                            .addComponent(Email)
                            .addComponent(Registro))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(TextEmailRegistro)
                    .addComponent(TextApellidoRegistro)
                    .addComponent(TextNombreRegistro, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(AbajoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbajoPanelLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(BotonRegistro))
                    .addGroup(AbajoPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(AbajoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ContraseñaRegistro)
                            .addComponent(UsuarioRegistro)
                            .addComponent(TextUsuarioRegistro)
                            .addComponent(TextContrasenaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(59, 59, 59))
        );
        AbajoPanelLayout.setVerticalGroup(
            AbajoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbajoPanelLayout.createSequentialGroup()
                .addGroup(AbajoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(AbajoPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UsuarioRegistro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextUsuarioRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(ContraseñaRegistro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextContrasenaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(BotonRegistro))
                    .addGroup(AbajoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AbajoPanelLayout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addComponent(Registro)
                            .addGap(57, 57, 57)
                            .addComponent(Nombre)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TextNombreRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(Apellido)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TextApellidoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(Email)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TextEmailRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(AbajoPanelLayout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MedioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AbajoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MedioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AbajoPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextNombreRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNombreRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNombreRegistroActionPerformed

    private void BotonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistroActionPerformed
        try{
            //Utilizamos los get y set
            Usuario usuario = new Usuario();
            usuario.setUsuario(TextUsuarioRegistro.getText());
            usuario.setContrasenia(TextContrasenaRegistro.getText());
            usuario.setNombre(TextNombreRegistro.getText());
            usuario.setApellido(TextApellidoRegistro.getText());
            usuario.setEmail(TextEmailRegistro.getText());
            
            usuarioLogica.crearUsuario(usuario);
            
            TextNombreRegistro.setText(null);
            TextApellidoRegistro.setText(null);
            TextUsuarioRegistro.setText(null);
            TextContrasenaRegistro.setText(null);
            TextEmailRegistro.setText(null);
            
            JOptionPane.showMessageDialog(AbajoPanel, "Se ha regristrado correctamente: " + usuario.getNombre(), "Registrar Administrador", JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(AbajoPanel, e.getMessage(), "Registrar Administrador", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonRegistroActionPerformed

    private void TextUsuarioRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextUsuarioRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextUsuarioRegistroActionPerformed

    private void IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesionActionPerformed
        try {
            if (usuarioLogica.validarUsuario(TextUsuario.getText(), TextContrasena.getText())) {
                JOptionPane.showMessageDialog(AbajoPanel, "Ingresaste con exito", "Iniciar Sesión", JOptionPane.INFORMATION_MESSAGE);
                
                this.setVisible(false);
                new InterfazHomePage().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(AbajoPanel, "Usuario y/o contraseña incorrectos", "Iniciar Sesión", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(AbajoPanel, e.getMessage());
        }
    }//GEN-LAST:event_IniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InterfazRegistrarAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InterfazRegistrarAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InterfazRegistrarAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InterfazRegistrarAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new InterfazRegistrarAdministrador().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AbajoPanel;
    private javax.swing.JLabel Apellido;
    private javax.swing.JButton BotonRegistro;
    private javax.swing.JLabel Contraseña;
    private javax.swing.JLabel ContraseñaRegistro;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel IconoRegistro;
    private javax.swing.JButton IniciarSesion;
    private javax.swing.JPanel MedioPanel;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Registro;
    private javax.swing.JTextField TextApellidoRegistro;
    private javax.swing.JPasswordField TextContrasena;
    private javax.swing.JPasswordField TextContrasenaRegistro;
    private javax.swing.JTextField TextEmailRegistro;
    private javax.swing.JTextField TextNombreRegistro;
    private javax.swing.JTextField TextUsuario;
    private javax.swing.JTextField TextUsuarioRegistro;
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel UsuarioRegistro;
    private javax.swing.Box.Filler filler1;
    // End of variables declaration//GEN-END:variables
}
