/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.usbcali.colegiousb.presentacion;

import co.edu.usbcali.colegiousb.logica.ActividadLogica;
import co.edu.usbcali.colegiousb.logica.IActividadLogica;
import co.edu.usbcali.colegiousb.logica.IMateriaLogica;
import co.edu.usbcali.colegiousb.logica.MateriaLogica;
import co.edu.usbcali.colegiousb.modelo.Actividad;
import javax.swing.JOptionPane;
/**
 *
 * @author FAVI
 */
public class InterfazCRUDActividad2 extends javax.swing.JFrame {
    private IActividadLogica actividadLogica = new ActividadLogica();
    private IMateriaLogica materiaLogica = new MateriaLogica();
    
    /**
     * Creates new form InterfazCRUDEstudiante
     */
    
    public InterfazCRUDActividad2() {
        initComponents();
        botonTransparente();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Registrar Actividad");
    }
    
    public void botonTransparente(){
        btnHome4.setOpaque(false);
        btnHome4.setBorderPainted(false);
        btnHome4.setContentAreaFilled(false);
        BotonCrearActividad.setOpaque(false);
        BotonCrearActividad.setBorderPainted(false);
        BotonCrearActividad.setContentAreaFilled(false);
        BotonLimpiarActividad.setOpaque(false);
        BotonLimpiarActividad.setBorderPainted(false);
        BotonLimpiarActividad.setContentAreaFilled(false);
        BotonVisualizarActividad.setOpaque(false);
        BotonVisualizarActividad.setBorderPainted(false);
        BotonVisualizarActividad.setContentAreaFilled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCompleto = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        TextActividad = new javax.swing.JLabel();
        IconoActividad = new javax.swing.JLabel();
        btnHome4 = new javax.swing.JButton();
        TextoCabecera = new javax.swing.JLabel();
        Datos = new javax.swing.JPanel();
        ActividadActividad = new javax.swing.JLabel();
        FechaActividad = new javax.swing.JLabel();
        ComboActividadActividad = new javax.swing.JComboBox<>();
        ActividadActividad1 = new javax.swing.JLabel();
        TextFechaActividad1 = new javax.swing.JTextField();
        TextIdActividad = new javax.swing.JTextField();
        TextIdMateriaActividad = new javax.swing.JTextField();
        FechaActividad1 = new javax.swing.JLabel();
        Operadores = new javax.swing.JPanel();
        BotonCrearActividad = new javax.swing.JButton();
        BotonVisualizarActividad = new javax.swing.JButton();
        BotonLimpiarActividad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelCompleto.setBackground(new java.awt.Color(79, 134, 193));
        PanelCompleto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(178, 218, 250));

        TextActividad.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TextActividad.setForeground(new java.awt.Color(0, 61, 112));
        TextActividad.setText("Actividad");

        IconoActividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/lista.png"))); // NOI18N

        btnHome4.setBackground(new java.awt.Color(178, 218, 250));
        btnHome4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/back.png"))); // NOI18N
        btnHome4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnHome4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IconoActividad)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(TextActividad)))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnHome4)
                .addGap(108, 108, 108)
                .addComponent(TextActividad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IconoActividad)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        PanelCompleto.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 530));

        TextoCabecera.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        TextoCabecera.setForeground(new java.awt.Color(255, 255, 255));
        TextoCabecera.setText("Sistema Registro De Actividades");
        PanelCompleto.add(TextoCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        Datos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        Datos.setForeground(new java.awt.Color(255, 255, 255));
        Datos.setOpaque(false);

        ActividadActividad.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ActividadActividad.setForeground(new java.awt.Color(255, 255, 255));
        ActividadActividad.setText("Id Actividad");

        FechaActividad.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        FechaActividad.setForeground(new java.awt.Color(255, 255, 255));
        FechaActividad.setText("Fecha");

        ComboActividadActividad.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ComboActividadActividad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quiz", "Examen", "Taller", "Participación", "Proyecto", "Exposición" }));

        ActividadActividad1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ActividadActividad1.setForeground(new java.awt.Color(255, 255, 255));
        ActividadActividad1.setText("Actividad");

        TextFechaActividad1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        TextIdActividad.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        TextIdMateriaActividad.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        FechaActividad1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        FechaActividad1.setForeground(new java.awt.Color(255, 255, 255));
        FechaActividad1.setText("Id Materia");

        javax.swing.GroupLayout DatosLayout = new javax.swing.GroupLayout(Datos);
        Datos.setLayout(DatosLayout);
        DatosLayout.setHorizontalGroup(
            DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ActividadActividad)
                            .addComponent(ActividadActividad1))
                        .addComponent(FechaActividad))
                    .addComponent(FechaActividad1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TextFechaActividad1)
                    .addComponent(ComboActividadActividad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextIdActividad)
                    .addComponent(TextIdMateriaActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );
        DatosLayout.setVerticalGroup(
            DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosLayout.createSequentialGroup()
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextIdActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ActividadActividad))
                .addGap(24, 24, 24)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ActividadActividad1)
                    .addComponent(ComboActividadActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FechaActividad)
                    .addComponent(TextFechaActividad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FechaActividad1)
                    .addComponent(TextIdMateriaActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        PanelCompleto.add(Datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 440, 220));

        Operadores.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Operadores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        Operadores.setOpaque(false);

        BotonCrearActividad.setBackground(new java.awt.Color(178, 218, 250));
        BotonCrearActividad.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BotonCrearActividad.setForeground(new java.awt.Color(0, 61, 112));
        BotonCrearActividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/anadir (1).png"))); // NOI18N
        BotonCrearActividad.setText("Crear");
        BotonCrearActividad.setBorderPainted(false);
        BotonCrearActividad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCrearActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCrearActividadActionPerformed(evt);
            }
        });

        BotonVisualizarActividad.setBackground(new java.awt.Color(178, 218, 250));
        BotonVisualizarActividad.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BotonVisualizarActividad.setForeground(new java.awt.Color(0, 61, 112));
        BotonVisualizarActividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/visualizacion-de-datos.png"))); // NOI18N
        BotonVisualizarActividad.setText("Visualizar");
        BotonVisualizarActividad.setBorderPainted(false);
        BotonVisualizarActividad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonVisualizarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVisualizarActividadActionPerformed(evt);
            }
        });

        BotonLimpiarActividad.setBackground(new java.awt.Color(178, 218, 250));
        BotonLimpiarActividad.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BotonLimpiarActividad.setForeground(new java.awt.Color(0, 61, 112));
        BotonLimpiarActividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbcali/colegiousb/presentacion/imagenes/limpieza-de-datos (1).png"))); // NOI18N
        BotonLimpiarActividad.setText("Limpiar");
        BotonLimpiarActividad.setBorderPainted(false);
        BotonLimpiarActividad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonLimpiarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarActividadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OperadoresLayout = new javax.swing.GroupLayout(Operadores);
        Operadores.setLayout(OperadoresLayout);
        OperadoresLayout.setHorizontalGroup(
            OperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperadoresLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(BotonCrearActividad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonVisualizarActividad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonLimpiarActividad)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        OperadoresLayout.setVerticalGroup(
            OperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperadoresLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(OperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonCrearActividad)
                    .addComponent(BotonVisualizarActividad)
                    .addComponent(BotonLimpiarActividad))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        PanelCompleto.add(Operadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 440, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCrearActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCrearActividadActionPerformed
        try{
            Actividad actividad = new Actividad();
            actividad.setId(TextIdActividad.getText());
            actividad.setActividad(ComboActividadActividad.getSelectedItem().toString());
            actividad.setFecha(TextFechaActividad1.getText());
            actividad.setMateria(materiaLogica.obtenerMateriaPorId(TextIdMateriaActividad.getText()));
            
            if (materiaLogica.obtenerMateriaPorId(TextIdMateriaActividad.getText()) == null) {
                JOptionPane.showMessageDialog(PanelCompleto, "El id de la materia no existe", "Registrar Actividad", JOptionPane.ERROR_MESSAGE);
            }
            
            if (TextIdActividad.getText().isEmpty() || TextFechaActividad1.getText().isEmpty() || TextIdMateriaActividad.getText().isEmpty()) {
                JOptionPane.showMessageDialog(PanelCompleto, "Todos los campos son obligatorios", "Registrar Actividad", JOptionPane.ERROR_MESSAGE);
            } 
            
            if (actividadLogica.validarActividadFecha(TextFechaActividad1.getText())) {
                JOptionPane.showMessageDialog(PanelCompleto, "La fecha no puede ser antigua", "Registrar Actividad", JOptionPane.ERROR_MESSAGE);
            } else if (actividadLogica.validarActividadId(actividad.getId())) {
                JOptionPane.showMessageDialog(PanelCompleto, "El Id debe ser único e irrepetible", "Registrar Actividad", JOptionPane.ERROR_MESSAGE);
            } else {
                actividadLogica.crearActividad(actividad);
                BotonLimpiarActividadActionPerformed(evt);
                JOptionPane.showMessageDialog(PanelCompleto, "Se ha regristado la actividad: " + actividad.getActividad(), "Registrar Actividad", JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(Exception e){
        }
    }//GEN-LAST:event_BotonCrearActividadActionPerformed

    private void BotonLimpiarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarActividadActionPerformed
        ComboActividadActividad.setSelectedItem(null);
        TextIdActividad.setText(null);
        TextFechaActividad1.setText(null);
        TextIdMateriaActividad.setText(null);
    }//GEN-LAST:event_BotonLimpiarActividadActionPerformed

    private void BotonVisualizarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVisualizarActividadActionPerformed
        this.setVisible(false);
        new InterfazCRUDActividad().setVisible(true);
    }//GEN-LAST:event_BotonVisualizarActividadActionPerformed

    private void btnHome4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome4ActionPerformed
        this.setVisible(false);
        new InterfazHomePage().setVisible(true);
    }//GEN-LAST:event_btnHome4ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InterfazCRUDEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InterfazCRUDEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InterfazCRUDEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InterfazCRUDEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new InterfazCRUDActividad2().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ActividadActividad;
    private javax.swing.JLabel ActividadActividad1;
    private javax.swing.JButton BotonCrearActividad;
    private javax.swing.JButton BotonLimpiarActividad;
    private javax.swing.JButton BotonVisualizarActividad;
    private javax.swing.JComboBox<String> ComboActividadActividad;
    private javax.swing.JPanel Datos;
    private javax.swing.JLabel FechaActividad;
    private javax.swing.JLabel FechaActividad1;
    private javax.swing.JLabel IconoActividad;
    private javax.swing.JPanel Operadores;
    private javax.swing.JPanel PanelCompleto;
    private javax.swing.JLabel TextActividad;
    private javax.swing.JTextField TextFechaActividad1;
    private javax.swing.JTextField TextIdActividad;
    private javax.swing.JTextField TextIdMateriaActividad;
    private javax.swing.JLabel TextoCabecera;
    private javax.swing.JButton btnHome4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
